services:
  db:
    image: mysql:8.0
    container_name: mysql-container-ms1order_api
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms1order_api
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysdocker
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app-ms1order_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ms1order_api?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      API_SECURITY_TOKEN_SECRET: 1234567
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: